# Generated by Django 3.0.8 on 2020-11-26 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
